/*
 * generated by Xtext unknown
 */
package net.akehurst.example.xtext.vertx.language.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class LanguageWebModule extends AbstractLanguageWebModule {
}
