/*
 * generated by Xtext unknown
 */
package net.akehurst.example.xtext.vertx.language.ide


/**
 * Use this class to register ide components.
 */
class MathIdeModule extends AbstractMathIdeModule {
}
