/*
 * generated by Xtext unknown
 */
package net.akehurst.example.xtext.vertx.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LanguageRuntimeModule extends AbstractLanguageRuntimeModule {
}
