/*
 * generated by Xtext 2.10.0
 */
package net.akehurst.example.xtext.vertx.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathRuntimeModule extends AbstractMathRuntimeModule {
}
